package com.example.tarot

object WaiteSmithDeck {

    val cards = listOf(

    Card(name="The Fool", image= "maj00.jpg", keywords=listOf( "Innocence", "New Beginnings", "Optimism")),
    Card(name="The Magician", image= "maj01.jpg", keywords=listOf( "Power", "Presence", "Clarity")),
    Card(name="The High Priestess", image= "maj02.jpg", keywords=listOf( "Intuition", "Subconscious", "Reflection")),
    Card(name="The Empress", image= "maj03.jpg", keywords=listOf( "Abundance", "Mothering", "Sensuality", "Nature")),
    Card(name="The Emperor", image= "maj04.jpg", keywords=listOf( "Order", "Accountability", "Authority", "Fathering")),
    Card(name="The Hierophant", image= "maj05.jpg", keywords=listOf( "Formal Learning", "Conformity", "Structure")),
    Card(name="The Lovers", image= "maj06.jpg", keywords=listOf( "Love", "Attraction", "Sexuality", "Strong Boundaries")),
    Card(name="The Chariot", image= "maj07.jpg", keywords=listOf( "Will", "Hard Power" )),
    Card(name="Strength", image= "maj08.jpg", keywords=listOf( "Soft Power", "Influence")),
    Card(name="The Hermit", image= "maj09.jpg", keywords=listOf( "Introspection", "Withdrawal", "Searching", "Solitude")),
    Card(name="Wheel of Fortune", image= "maj10.jpg", keywords=listOf( "Destiny", "Turning Point", "Larger Forces At Work")),
    Card(name="Justice", image= "maj11.jpg", keywords=listOf( "Justice", "Responsibility", "Cause and Effect")),
    Card(name="The Hanged Man", image= "maj12.jpg", keywords=listOf( "Letting Go", "Reversal", "Sacrifice")),
    Card(name="Death", image= "maj13.jpg", keywords=listOf( "Ending", "Change", "Humility")),
    Card(name="Temperance", image= "maj14.jpg", keywords=listOf( "Temperance", "Balance")),
    Card(name="The Devil", image= "maj15.jpg", keywords=listOf( "Illusion", "Materialism", "Ignorance", "Self-Desctructive Choices")),
    Card(name="The Tower", image= "maj16.jpg", keywords=listOf( "Shattering the Status Quo", "Ego Death", "Dramatic Change", "Loss of Illusions")),
    Card(name="The Star", image= "maj17.jpg", keywords=listOf( "Hope", "Serenity", "Generosity")),
    Card(name="The Moon", image= "maj18.jpg", keywords=listOf( "Illusion", "Imagination", "Charm")),
    Card(name="The Sun", image= "maj19.jpg", keywords=listOf( "Enlightenment", "Power", "On Top Of The World")),
    Card(name="Judgement", image= "maj20.jpg", keywords=listOf( "Judgment", "Forgiveness", "Rebirth")),
    Card(name="The World", image= "maj21.jpg", keywords=listOf( "Integration", "Fulfillment", "Connectedness")),
    Card(name="Ace of Wands", image= "wands01.jpg", keywords=listOf( "Creative Force", "Enthusiasm", "Confidence", "Courage")),
    Card(name="Two of Wands", image= "wands02.jpg", keywords=listOf( "Personal Power", "Boldness", "Originality")),
    Card(name="Three of Wands", image= "wands03.jpg", keywords=listOf( "Exploration", "Foresight", "Leadership")),
    Card(name="Four of Wands", image= "wands04.jpg", keywords=listOf( "Celebration", "Freedom", "Excitement")),
    Card(name="Five of Wands", image= "wands05.jpg", keywords=listOf( "Disagreement", "Competition", "Hassles")),
    Card(name="Six of Wands", image= "wands06.jpg", keywords=listOf( "Triumph", "Acclaim", "Pride")),
    Card(name="Seven of Wands", image= "wands07.jpg", keywords=listOf( "Aggression", "Defiance", "Conviction")),
    Card(name="Eight of Wands", image= "wands08.jpg", keywords=listOf( "Quick Action", "Conclusion", "News")),
    Card(name="Nine of Wands", image= "wands09.jpg", keywords=listOf( "Defensiveness", "Perseverance", "Stamina")),
    Card(name="Ten of Wands", image= "wands10.jpg", keywords=listOf( "Overextending", "Burdens", "Struggle")),
    Card(name="Page of Wands", image= "wands11.jpg", keywords=listOf( "Explore Creativity", "Be Enthusiastic", "Trust and Be Confident", "Have Courage")),
    Card(name="Knight of Wands", image= "wands12.jpg", keywords=listOf( "Charming ~ Superficial", "Self-Confident ~ Cocky", "Daring ~ Foolhardy", "Adventurous ~ Restless", "Passionate ~ Hot-Tempered")),
    Card(name="Queen of Wands", image= "wands13.jpg", keywords=listOf( "Attractive", "Energetic", "Cheerful", "Popular")),
    Card(name="King of Wands", image= "wands14.jpg", keywords=listOf( "Creative", "Forceful", "Charismatic", "Bold")),
    Card(name="Ace of Cups", image= "cups01.jpg", keywords=listOf( "Emotional Force", "Intiution")),
    Card(name="Two of Cups", image= "cups02.jpg", keywords=listOf( "Attraction", "Connection")),
    Card(name="Three of Cups", image= "cups03.jpg", keywords=listOf( "Friendship", "Community", "Joy")),
    Card(name="Four of Cups", image= "cups04jpg", keywords=listOf( "Apathy", "Turning Within", "Introspection", "Obliviousness")),
    Card(name="Five of Cups", image= "cups05.jpg", keywords=listOf( "Grief", "Loss", "Focus on the Negative")),
    Card(name="Six of Cups", image= "cups06.jpg", keywords=listOf( "Innocence", "Childhood", "Sweetness")),
    Card(name="Seven of Cups", image= "cups07.jpg", keywords=listOf( "Options", "Distractions", "Deception")),
    Card(name="Eight of Cups", image= "cups08.jpg", keywords=listOf( "Letting Go", "Moving On", "Detachment")),
    Card(name="Nine of Cups", image= "cups09.jpg", keywords=listOf( "Pleasure", "Self-Satisfaction", "Wish Card")),
    Card(name="Ten of Cups", image= "cups10.jpg", keywords=listOf( "Family", "Love", "Joy")),
    Card(name="Page of Cups", image= "cups11.jpg", keywords=listOf( "Emotion", "Intuition", "Love")),
    Card(name="Knight of Cups", image= "cups12.jpg", keywords=listOf( "Intuitive ~ Haphazard", "Romantic ~ Saccharine", "Emotional ~ Self-Absorbed")),
    Card(name="Queen of Cups", image= "cups13.jpg", keywords=listOf( "Understanding", "Empathetic", "Sweet", "Wise")),
    Card(name="King of Cups", image= "cups14.jpg", keywords=listOf( "Diplomatic", "Connected", "Patient")),
    Card(name="Ace of Swords", image= "swords01.jpg", keywords=listOf( "Mental Force")),
    Card(name="Two of Swords", image= "swords02.jpg", keywords=listOf( "Feeling Blocked", "Willful Blindness")),
    Card(name="Three of Swords", image= "swords03.jpg", keywords=listOf( "Loneliness", "Heartbreak", "Abandonment", "Betrayal")),
    Card(name="Four of Swords", image= "swords04.jpg", keywords=listOf( "Rest", "Preparation", "The Calm Before the Storm")),
    Card(name="Five of Swords", image= "swords05.jpg", keywords=listOf( "Conflict", "Self-Interest", "Loss of Connection")),
    Card(name="Six of Swords", image= "swords06.jpg", keywords=listOf( "Moving On", "Escape", "Seeking Refuge")),
    Card(name="Seven of Swords", image= "swords07.jpg", keywords=listOf( "Running Away", "Breaking Rules", "Theft")),
    Card(name="Eight of Swords", image= "swords08.jpg", keywords=listOf( "Captivity", "Bound", "Stuck")),
    Card(name="Nine of Swords", image= "swords09.jpg", keywords=listOf( "Guilty Conscience", "Painful Memories", "Repression")),
    Card(name="Ten of Swords", image= "swords10.jpg", keywords=listOf( "Victimhood", "Drama", "Dark Humor")),
    Card(name="Page of Swords", image= "swords11.jpg", keywords=listOf( "Smart", "Ethical", "Be Straightforward")),
    Card(name="Knight of Swords", image= "swords12.jpg", keywords=listOf( "Straightforward ~ Blunt", "Rational ~ Lacking Empathy", "Smart ~ Pointy-Headed", "Ethical ~ Self-Righteous")),
    Card(name="Queen of Swords", image= "swords13.jpg", keywords=listOf( "No-Nonsense", "Astute", "Keen", "Articulate","Sees Through BS")),
    Card(name="King of Swords", image= "swords14.jpg", keywords=listOf( "Smart", "Just", "Intellectual", "Straightforward", "Master of Words")),
    Card(name="Ace of Pentacles", image= "pents01.jpg", keywords=listOf( "Material Force", "Practical Matters", "Managing Things Well")),
    Card(name="Two of Pentacles", image= "pents02.jpg", keywords=listOf( "Ease", "Grace", "Balance")),
    Card(name="Three of Pentacles", image= "pents03.jpg", keywords=listOf( "Teamwork", "Cooperation", "Different Spheres Coming Together")),
    Card(name="Four of Pentacles", image= "pents04.jpg", keywords=listOf( "Maintaining Control", "Hanging On To Something")),
    Card(name="Five of Pentacles", image= "pents05.jpg", keywords=listOf( "Suffering", "Deprivation", "Time In The Wilderness")),
    Card(name="Six of Pentacles", image= "pents06.jpg", keywords=listOf( "To Have and Have Not", "Judging Worthiness")),
    Card(name="Seven of Pentacles", image= "pents07.jpg", keywords=listOf( "Stepping Back", "Assessing")),
    Card(name="Eight of Pentacles", image= "pents08.jpg", keywords=listOf( "Persistence", "Craftmanship", "Focus", "Enjoying One's Work")),
    Card(name="Nine of Pentacles", image= "pents09.jpg", keywords=listOf( "Mastering Animal Instincts", "Having Nice Things", "Self-Control")),
    Card(name="Ten of Pentacles", image= "pents10.jpg", keywords=listOf( "Wealth", "Being Conservative")),
    Card(name="Page of Pentacles", image= "pents11.jpg", keywords=listOf( "Curiosity for Things", "Practicality", "Trustworthy")),
    Card(name="Knight of Pentacles", image= "pents12.jpg", keywords=listOf( "Practical ~ Unimaginative", "Persistent ~ Pig-Headed", "Trustworthy ~ Overly Literal / Predictable", "Diligent ~ Obsessive")),
    Card(name="Queen of Pentacles", image= "pents13.jpg", keywords=listOf( "Caring", "Practical", "Of Service")),
    Card(name="King of Pentacles", image= "pents14.jpg", keywords=listOf( "Competent", "Grounded", "All Business"))
    )
}